create KeyboardManager
entire-development/epic-dungeons pull request #38
Opened 2024-03-08 18:27 UTC by chimort

2024-03-08 20:07 UTC, d0gied requested changes

2024-03-08 20:07 UTC, d0gied commented on src/gui_controller/keyboard_manager/keyboard_manager.h
> +class KeyboardManager : public State {
Это не State, а просто утилита

2024-03-08 20:07 UTC, d0gied commented on src/gui_controller/keyboard_manager/keyboard_manager.h
> +    bool isPressed(keyboard::Key key) {
const keyboard::Key& key

2024-03-08 20:07 UTC, d0gied commented on src/gui_controller/keyboard_manager/keyboard_manager.h
> +            m_cur_state[i] = keyboard::isPressed(keyboard::Key(i));
При таком порядке обновления в обоих массивах будет просто текущий isPressed, нужно сначала перемещать, потом обновлять текущее

2024-03-08 20:07 UTC, d0gied commented on src/gui_controller/keyboard_manager/keyboard_manager.h
> +    std::vector<bool> m_cur_state;
Нигде не задаются размеры этих массивов

2024-03-09 05:56 UTC, d0gied approved these changes

2024-03-09 05:58 UTC, d0gied requested changes

2024-03-09 05:58 UTC, d0gied commented on src/gui_controller/keyboard_manager/keyboard_manager.h
> +#include "gui_controller/controller.h"
include не используется

2024-03-09 05:58 UTC, d0gied commented on src/gui_controller/keyboard_manager/keyboard_manager.h
> +    bool isPressed(const keyboard::Key &key) {
функции ничего не меняют, поэтому должны быть const

2024-03-09 12:34 UTC, chimort commented
Не будет лучше векторы на массивы заменить, потому что мы размер знаем?

2024-03-10 06:21 UTC, d0gied approved these changes

2024-03-10 06:22 UTC, merged